// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPnUOkcm6TPfbsNV7bFcWU_7Za4fbkb7s',
    appId: '1:838972151248:android:12fa22b8ab8a83ce5155d5',
    messagingSenderId: '838972151248',
    projectId: 'campuspulse-949fe',
    storageBucket: 'campuspulse-949fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBgCJOjdA8Zbrr5t_3kOv2n6DFHr2qZik',
    appId: '1:838972151248:ios:9534d2557e17452a5155d5',
    messagingSenderId: '838972151248',
    projectId: 'campuspulse-949fe',
    storageBucket: 'campuspulse-949fe.firebasestorage.app',
    iosBundleId: 'com.example.campuspulse',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2IT8A025MsqOH9cGfDygo8vX2Hy1igSk',
    appId: '1:838972151248:web:e08eee73d06c5b625155d5',
    messagingSenderId: '838972151248',
    projectId: 'campuspulse-949fe',
    authDomain: 'campuspulse-949fe.firebaseapp.com',
    storageBucket: 'campuspulse-949fe.firebasestorage.app',
    measurementId: 'G-PYYVXV55B3',
  );

}